version: '1.0'

services:
  client:
    build: ./frontend
    container_name: fontendapp
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true

  server:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
