version: '3.3'

services:
  client:
    build: ./frontend
    container_name: client
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true

  server:
    build: ./backend
    container_name: server
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
